import Appshell  from "@/components/appshell";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function Home() {
  return (
    <Appshell>
      Hello World
    </Appshell>
  )
}