import Appshell  from "@/components/appshell";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <Appshell>
      <div>
        <h1>Create Next App</h1>
      </div>
    </Appshell>
  )
}